//
// 数値処理
// Generated by ChatGPT
//

/**
 * min以上max以下の整数を生成
 * @param {number} min 下限
 * @param {number} max 上限
 * @returns 生成された数値
 */
export function nonZeroRandom(min, max) {
    const randInt = (min, max) => { return Math.floor(Math.random() * (max - min + 1)) + min; };
    const sign = (Math.random() < 0.5) ? 1 : -1;
    return randInt(min, max) * sign;
}

/**
 * ユークリッドの互除法により最大公約数を計算する
 * @param {number} a 数字1
 * @param {number} b 数字2
 * @returns 最大公約数
 */
export function euclideanGCD(a, b) {
    while (b !== 0) {
        const temp = b;
        b = a % b;
        a = temp;
    }
    return a;
}

/**
 * ax + by = gcd(a, b) となる x, y を求める
 * @param {number} a 数字1
 * @param {number} b 数字2
 * @returns 演算結果
 */
export function extGCD(a, b) {
    let x = 0;
    let y = 0;

    if (b === 0) {
        x = 1;
        y = 0;
        return [a, x, y];
    }

    const [d, x1, y1] = extGCD(b, a % b);
    x = y1;
    y = x1 - Math.floor(a / b) * y1;

    return [d, x, y];
}
